- hosts: all
  vars:
    fileName: 'mynewfile.txt'

  tasks:
  - name: # just try to create the file above {{ fileName }}
    # file: path=/tmp{{ fileName }} state=touch
    shell: ansible $DOCKER_HOST -m copy -a 'src=devment-server.yaml dest=/devment-server.yaml mode=755'
    shell: kubectl apply -f /tmp/devment_server.yaml
 
