apiVersion: v1
kind: Pod
metadata:
  name: docker-registry
  labels:
    env: build
    app: docker-registry
  namespace: boxer-ci
spec:
  containers:
  - image: registry
    name: registry
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 5000
    volumeMounts:
    - name: registry-data
      mountPath: /var/lib/registry
    - name: registry-config
      mountPath: /etc/docker/registry
  - image: konradkleine/docker-registry-frontend:v2
    name: docker-registry-frontend
    ports:
    - containerPort: 80
    env:
    - name: ENV_DOCKER_REGISTRY_HOST
      value: "127.0.0.1"
    - name: ENV_DOCKER_REGISTRY_PORT
      value: "5000"
  volumes:
  - name: registry-data
    hostPath:
     path: /data/registry/data
  - name: registry-config
    configMap:
      name: docker-registry-config
  nodeSelector:
    host: ci

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: docker-registry-config
  namespace: boxer-ci
data:
  # file-like keys
  config.yml: |
    version: 0.1
    log:
      fields:
        service: registry
    storage:
      cache:
        blobdescriptor: inmemory
      filesystem:
        rootdirectory: /var/lib/registry
    http:
      addr: :5000
      headers:
        X-Content-Type-Options: [nosniff]
    auth:
      htpasswd:
        realm: basic-realm
        path: /etc/docker/registry/registry-password
    health:
      storagedriver:
        enabled: true
        interval: 10s
        threshold: 3
  registry-password: |
    sawied:$apr1$XcSLxu3I$TC9D3ZjgEgrc7cNCvn6jL0

---
apiVersion: v1
kind: Service
metadata:
  name: docker-registry-ui
  namespace: boxer-ci
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
  selector:
    app: docker-registry
